import { useMemo, useState } from 'react'
import { type ActivityData,type ActivityPeriod,useActivityView } from '../hooks/useActivityView'
const periods:Array<{value:ActivityPeriod;label:string}>=[{value:'12m',label:'12 months'},{value:'24m',label:'24 months'},{value:'5y',label:'5 years'},{value:'all',label:'All time'}]
export function ActivityView(){const[period,setPeriod]=useState<ActivityPeriod>('12m');const activity=useActivityView(period);return <><div className="view-toolbar"><div><p className="eyebrow">Measured activity</p><h2>Commit activity</h2></div><label className="period-filter"><span>Period</span><select value={period} onChange={e=>setPeriod(e.target.value as ActivityPeriod)}>{periods.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div>{activity.status==='loading'?<section className="dashboard-loading"><div className="loading-indicator"/><p>Loading activity…</p></section>:null}{activity.status==='error'?<section className="dashboard-error"><h2>Activity data could not be loaded.</h2><p>{activity.error}</p></section>:null}{activity.status==='ready'?<ActivityContent data={activity.data}/>:null}</>}
function ActivityContent({data}:{data:ActivityData}){const[selected,setSelected]=useState<{title:string;commits:number;projects?:number;projectNames?:string[]}|null>(null);const maxY=Math.max(1,...data.commitsPerYear.map(x=>x.commits)),maxM=Math.max(1,...data.commitsPerMonth.map(x=>x.commits));return <>
<section className="metric-grid"><Metric label="Commits" value={fmt(data.commitCount)}/><Metric label="Active projects" value={fmt(data.activeProjects)}/><Metric label="Average commit size" value={data.commitSizeStatisticsAvailable?`${fmt(Math.round(data.averageCommitSize))} lines`:'Not available'}/><Metric label="Additions" value={data.commitSizeStatisticsAvailable?`+${fmt(data.additions)}`:'Not available'}/><Metric label="Deletions" value={data.commitSizeStatisticsAvailable?`−${fmt(data.deletions)}`:'Not available'}/></section>
<section className="dashboard-section"><span className="card-kicker">Yearly trend</span><h2>Commits per year</h2><div className="bar-chart">{data.commitsPerYear.map(x=><Bar key={x.year} label={String(x.year)} value={x.commits} max={maxY} onClick={()=>setSelected({title:String(x.year),commits:x.commits,projects:x.activeProjects,projectNames:x.projects})}/>)}</div></section>
<section className="dashboard-section"><span className="card-kicker">Monthly trend</span><h2>Commits per month</h2><div className="bar-chart bar-chart-scroll">{data.commitsPerMonth.map(x=><Bar key={x.month} label={formatMonth(x.month)} value={x.commits} max={maxM} secondary={`${x.activeProjects} active project${x.activeProjects===1?'':'s'}`} onClick={()=>setSelected({title:formatMonth(x.month),commits:x.commits,projects:x.activeProjects,projectNames:x.projects})}/>)}</div>{selected?<div className="activity-drilldown"><strong>{selected.title}</strong><span>{fmt(selected.commits)} commits{selected.projects!==undefined?` across ${selected.projects} active projects`:''}</span>{selected.projectNames?.length?<span>{selected.projectNames.slice(0,20).join(' · ')}{selected.projectNames.length>20?' …':''}</span>:null}</div>:null}</section>
<ProjectTimeline projects={data.projectsOverTime}/>
<section className="dashboard-section activity-period-note"><span className="card-kicker">Activity period</span><p>{data.firstActivityAt&&data.lastActivityAt?`${formatDate(data.firstActivityAt)} – ${formatDate(data.lastActivityAt)}`:'No activity in selected period'}</p></section></>}
function ProjectTimeline({projects}:{projects:ActivityData['projectsOverTime']}){const sorted=useMemo(()=>[...projects].sort((a,b)=>new Date(a.firstActivityAt).getTime()-new Date(b.firstActivityAt).getTime()),[projects]);const months=useMemo(()=>{if(!sorted.length)return[];const first=new Date(Math.min(...sorted.map(x=>new Date(x.firstActivityAt).getTime())));const last=new Date(Math.max(...sorted.map(x=>new Date(x.lastActivityAt).getTime())));const out:string[]=[];let y=first.getUTCFullYear(),m=first.getUTCMonth();while(y<last.getUTCFullYear()||(y===last.getUTCFullYear()&&m<=last.getUTCMonth())){out.push(`${y}-${String(m+1).padStart(2,'0')}`);m++;if(m===12){m=0;y++}}return out},[sorted]);if(!sorted.length)return null;return <section className="dashboard-section"><span className="card-kicker">Project timeline</span><h2>Projects over time</h2><p className="settings-intro">Each cell is one month. Stronger cells mean more commits, so starts, endings and periods of high activity are visible together.</p><div className="project-time-scroll"><div className="project-time-header"><span>Project</span><div className="project-time-months">{months.map((m,i)=><span key={m}>{i%12===0?m.slice(0,4):''}</span>)}</div><span>Commits</span></div>{sorted.map(x=>{const byMonth=new Map(x.monthlyActivity.map(v=>[v.month,v.commits]));const max=Math.max(1,...x.monthlyActivity.map(v=>v.commits));return <div className="project-time-row" key={x.repositoryId}><span className="project-time-name">{x.repositoryName}</span><div className="project-time-months">{months.map(m=>{const v=byMonth.get(m)||0;return <span key={m} className={`project-time-cell ${v?'project-time-cell-active':''}`} style={v?{opacity:0.2+0.8*(v/max)}:undefined} title={`${m}: ${v} commits`}/>} )}</div><span>{fmt(x.commits)}</span></div>})}</div></section>}
function Metric({label,value}:{label:string;value:string}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong></article>}
function Bar({label,value,max,secondary,onClick}:{label:string;value:number;max:number;secondary?:string;onClick?:()=>void}){const width=Math.max(2,Math.round(value/max*100));return <button type="button" className="bar-row bar-row-button" onClick={onClick}><div className="bar-label"><strong>{label}</strong>{secondary?<span>{secondary}</span>:null}</div><div className="bar-track"><div className="bar-fill" style={{width:`${width}%`}}/></div><span className="bar-value">{fmt(value)}</span></button>}
const fmt=(v:number)=>new Intl.NumberFormat().format(v);const formatMonth=(m:string)=>new Intl.DateTimeFormat(undefined,{month:'short',year:'2-digit'}).format(new Date(`${m}-01T00:00:00Z`));const formatDate=(v:string)=>new Intl.DateTimeFormat(undefined,{year:'numeric',month:'short',day:'numeric'}).format(new Date(v))
