import { useState } from 'react'
import { type ActivityData,type ActivityPeriod,useActivityView } from '../hooks/useActivityView'
const periods:Array<{value:ActivityPeriod;label:string}>=[{value:'12m',label:'12 months'},{value:'24m',label:'24 months'},{value:'5y',label:'5 years'},{value:'all',label:'All time'}]
export function ActivityView(){const[period,setPeriod]=useState<ActivityPeriod>('12m');const activity=useActivityView(period);return <><div className="view-toolbar"><div><p className="eyebrow">Measured activity</p><h2>Commit activity</h2></div><label className="period-filter"><span>Period</span><select value={period} onChange={e=>setPeriod(e.target.value as ActivityPeriod)}>{periods.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div>{activity.status==='loading'?<section className="dashboard-loading"><div className="loading-indicator"/><p>Loading activity…</p></section>:null}{activity.status==='error'?<section className="dashboard-error"><h2>Activity data could not be loaded.</h2><p>{activity.error}</p></section>:null}{activity.status==='ready'?<ActivityContent data={activity.data}/>:null}</>}
function ActivityContent({data}:{data:ActivityData}){const[selected,setSelected]=useState<{title:string;commits:number;projects?:number;projectNames?:string[]}|null>(null);const maxY=Math.max(1,...data.commitsPerYear.map(x=>x.commits)),maxM=Math.max(1,...data.commitsPerMonth.map(x=>x.commits));return <>
<section className="metric-grid"><Metric label="Commits" value={fmt(data.commitCount)}/><Metric label="Active projects" value={fmt(data.activeProjects)}/><Metric label="Average commit size" value={data.commitSizeStatisticsAvailable?`${fmt(Math.round(data.averageCommitSize))} lines`:'Not available'}/><Metric label="Additions" value={data.commitSizeStatisticsAvailable?`+${fmt(data.additions)}`:'Not available'}/><Metric label="Deletions" value={data.commitSizeStatisticsAvailable?`−${fmt(data.deletions)}`:'Not available'}/></section>
<section className="dashboard-section"><span className="card-kicker">Yearly trend</span><h2>Commits per year</h2><div className="bar-chart">{data.commitsPerYear.map(x=><Bar key={x.year} label={String(x.year)} value={x.commits} max={maxY} onClick={()=>setSelected({title:String(x.year),commits:x.commits,projects:x.activeProjects,projectNames:x.projects})}/>)}</div></section>
<section className="dashboard-section"><span className="card-kicker">Monthly trend</span><h2>Commits per month</h2><div className="bar-chart bar-chart-scroll">{data.commitsPerMonth.map(x=><Bar key={x.month} label={formatMonth(x.month)} value={x.commits} max={maxM} secondary={`${x.activeProjects} active project${x.activeProjects===1?'':'s'}`} onClick={()=>setSelected({title:formatMonth(x.month),commits:x.commits,projects:x.activeProjects,projectNames:x.projects})}/>)}</div>{selected?<div className="activity-drilldown"><strong>{selected.title}</strong><span>{fmt(selected.commits)} commits{selected.projects!==undefined?` across ${selected.projects} active projects`:''}</span>{selected.projectNames?.length?<span>{selected.projectNames.slice(0,20).join(' · ')}{selected.projectNames.length>20?' …':''}</span>:null}</div>:null}</section>
<section className="dashboard-section activity-period-note"><span className="card-kicker">Activity period</span><p>{data.firstActivityAt&&data.lastActivityAt?`${formatDate(data.firstActivityAt)} – ${formatDate(data.lastActivityAt)}`:'No activity in selected period'}</p></section></>}
function Metric({label,value}:{label:string;value:string}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong></article>}
function Bar({label,value,max,secondary,onClick}:{label:string;value:number;max:number;secondary?:string;onClick?:()=>void}){const width=Math.max(2,Math.round(value/max*100));return <button type="button" className="bar-row bar-row-button" onClick={onClick}><div className="bar-label"><strong>{label}</strong>{secondary?<span>{secondary}</span>:null}</div><div className="bar-track"><div className="bar-fill" style={{width:`${width}%`}}/></div><span className="bar-value">{fmt(value)}</span></button>}
const fmt=(v:number)=>new Intl.NumberFormat().format(v);const formatMonth=(m:string)=>new Intl.DateTimeFormat(undefined,{month:'short',year:'2-digit'}).format(new Date(`${m}-01T00:00:00Z`));const formatDate=(v:string)=>new Intl.DateTimeFormat(undefined,{year:'numeric',month:'short',day:'numeric'}).format(new Date(v))
